name = "gpsc-v2"
main = "worker.js"
compatibility_date = "2026-01-15"

[[d1_databases]]
binding = "DB"
database_name = "gpsc_v2_db"
database_id = "308c09e8-daa2-40ed-a68b-6a8ae3e158aa"

[[kv_namespaces]]
binding = "KV"
id = "1a154163dd614f8da7d889b5aa04701b"
